version: "3.5"
services:
  alexandreclayton-myzap2-dev:
    build:
      context: .
      target: alexandreclayton-myzap2-dev
    container_name: alexandreclayton-myzap2-dev
    working_dir: /usr/src/app
    volumes:
      - ${PATH_LOCAL}:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      backend:
        aliases:
          - alexandreclayton-myzap2-dev

#  myzap_2prod:
#    build: 
#      context: .
#      target: myzap_2prod
#    container_name: myzap_2prod
#    image: gcr.io/maisagil/myzap
#    ports:
#      - ${HOST_PORT}:${HOST_PORT}
#    networks:
#      backend:
#        aliases:
#          - myzap_2prod
networks:
  backend:
    name: alexandreclayton-myzap2-networks

# Build
# docker-compose up --build -d
